preset: laravel

linting: true

enabled:
  - strict
  - align_double_arrow
  - align_equals
  - phpdoc_order
  - phpdoc_separation
  - short_array_syntax

finder:
  name:
    - "*.php"
  exclude:
    - "public"
    - "resources"
    - "tests"
    - "_ide_helper.php"