language: php

php:
  # - '5.6'
  - '7.0'
  # - '7.1'

sudo: false

before_script:
  - cp .env.example .env
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit --exclude-group=integrations

notifications:
  email:
    recipients:
      - hello@handesk.io
    on_success: never
    on_failure: always